format_version: 9
environments:
  catalog-service-api:
    pipelines:
      - catalog-service-api-dev
pipelines:
  catalog-service-api-dev:
    group: catalog-service-api
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-config:
        git: git@github.com:suraz37/docker-nginx-php-mysql-redis.git
        shallow_clone: false
        auto_update: false
        branch: master
        destination: catalog-service-api
        ignore_for_scheduling: true
    stages:
    - deploy-run:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          deploy-run:
            timeout: 0
            resources:
              - ctos-MacBook-Pro.local
            tasks:
              - script: virtualenv ~/.hopvenv -p python3.5 && source ~/.hopvenv/bin/activate && make test
              - exec:
                  arguments:
                    - -c
                    - pip install -r requirements.txt
                    - pip install --target ./package -r requirements.txt
                    - chmod -R 755 *
                    - cd package 
                    - zip -r9 ../function.zip .
                  command: bash
                  working_directory: .
                  run_if: passed
