format_version: 9
environments:
  catalog-service-api:
    pipelines:
      - catalog-service-api-dev
pipelines:
  catalog-service-api-dev:
    group: catalog-service-api
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-config:
        git: git@github.com:suraz37/docker-nginx-php-mysql-redis.git
        shallow_clone: false
        auto_update: false
        branch: master
        destination: catalog-service-api
        ignore_for_scheduling: true
    stages:
    - deploy-run:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          deploy-run:
            timeout: 0
            resources:
              - ctos-MacBook-Pro.local
            tasks:
              - exec:
                  arguments:
                    - -c
                    - docker run -i --rm python:3.7-alpine  pip install parse pip install  requests
                    - apk update
                    - apk add git
                    - apk add zip
                    - chmod -R 755 *
                    - cd package 
                    - zip -r9 ../function.zip 
                    - virtualenv v-env
                    - source v-env/bin/activate
                    - deactivate
                    - cd ./v-env/lib/python3.7/site-packages/
                    - zip -r9 ../../../../function.zip 
                    - aws lambda update-function-configuration --function-name f1 --environment Variables={KeyName1=string,KeyName2=string} --region r1
                    - aws lambda update-function-code --function-name f1 --zip-file fileb://function.zip --region r1
                    - aws lambda publish-version --function-name f1 --description 11 --region r1
                  command: bash
                  working_directory: .
                  run_if: passed
