format_version: 9
environments:
  catalog-service-api:
    pipelines:
      - catalog-service-api-gocd
pipelines:
  catalog-service-api-gocd:
    group: catalog-service-api
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      qa-run:
        git: git@bitbucket.org:suraz37/goci.git
        shallow_clone: false
        auto_update: false
        branch: master
        destination: catalog-service-api
    stages:
    - deploy-run:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: true
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          deploy-run:
            timeout: 0
            resources:
            - image-builder-3
            tasks:
            - exec:
                arguments:
                - -c
                - eval $(pip install -r requirements.txt
pip install --target ./package -r requirements.txt)
                - ''
                command: bash
                run_if: passed

