format_version: 10
pipelines:
  my-pipeline-name:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-9519e34:
        git: git@github.com:suraz37/goci.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - my-staging:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-test-job:
            timeout: 0
            environment_variables:
              plain-vari: var1
            secure_variables:
              sec_variables: AES:zTo4T9mvua2YnTxeSZgrfQ==:lQuHjw6GpovvRwO0qHQryw==
            tasks:
            - exec:
                command: /bin/python3
                run_if: passed
