format_version: 9
environments:
  catalog-service-api:
    pipelines:
      - catalog-service-api-dev
pipelines:
  catalog-service-api-dev:
    group: catalog-service-api
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-config:
        git: git@bitbucket.org:suraz37/goci.git
        shallow_clone: false
        auto_update: false
        branch: master
        destination: catalog-service-api
        ignore_for_scheduling: true
    stages:
    - deploy-run:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          deploy-run:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - ls
                command: bash
                run_if: passed
            - plugin:
                    configuration:
                      id: slack.task
                      version: "2.0"
                    options:
                      Message: ""
                      IconOrEmoji: ""
                      Channel: cds-deployer
                      Color: ""
                      DisplayName: GO-BOT
                      Title: 🎉 Completed Dev Deployment
                      ColorType: Good
                      MarkdownInText: ""
                      FailOnError: ""
                      ChannelType: Channel
                    run_if: passed
            - plugin:
                configuration:
                  id: slack.task
                  version: "2.0"
                options:
                  Message: ""
                  IconOrEmoji: ""
                  Channel: cds-deployer
                  Color: ""
                  DisplayName: GO-BOT
                  Title: 🔥 Failed  Dev Deployment
                  ColorType: Danger
                  MarkdownInText: ""
                  FailOnError: ""
                  ChannelType: Channel
                run_if: failed
