format_version: 9
environments:
  catalog-service-api:
    pipelines:
      - catalog-service-api-dev
pipelines:
  catalog-service-api-dev:
    group: catalog-service-api
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      deploy-run:
        git: git@bitbucket.org:suraz37/goci.git
        shallow_clone: false
        auto_update: false
        branch: master
        destination: catalog-service-api
        stage: build-image
        ignore_for_scheduling: true
    stages:
    - deploy-run:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          deploy-run:
            timeout: 0
            resources:
            - image-builder-3
            tasks:
            - exec:
                arguments:
                - -c
                - eval $(pip install -r requirements.txt
                command: bash
                run_if: passed
