on: [push, pull_request]

pipelines:
  lambda-template:
    group: webops
    label_template: "${COUNT}"
    materials:
      lambda-template-git:
        git: git@github.com:ukparliament/lambda-template.git
        branch: master
        auto_update: true
    stages:
      - test:
          jobs:
            build:
                runs-on: ubuntu-latest

                steps:
                - uses: actions/checkout@v1
                - name: Set up Python 3.7
                    uses: actions/setup-python@v1
                    with:
                    python-version: 3.7
                - name: Install dependencies
                    run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

                - name: Lint with pylint
                    run: |
                    pip install pylint
                    find . -type f -name "*.py" | xargs python -m pylint
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy

environments:
  Web.DEVCI:
    pipelines:
      - lambda-template
