format_version: 9
environments:
  maintainance:
    pipelines:
      - gift-gocd
pipelines:
  gift-gocd:
    group: maintainance
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      qa-run:
        git: git@bitbucket.org:centraltechnology/cds-core1.git
        shallow_clone: false
        auto_update: false
        branch: master
        destination: cds-qa
      testrail_runner:
        git: git@bitbucket.org:centraltechnology/testrail_runner1.git
        shallow_clone: false
        auto_update: false
        branch: master
        destination: etc
      git-7180be5:
        git: git@bitbucket.org:centraltechnology/qa-config1.git
        shallow_clone: false
        auto_update: false
        branch: master
        destination: qa-config
    stages:
    - qa-run:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: true
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          qa-run:
            timeout: 0
            tabs:
              Test-Result: cds-qa/Report0/report.html
            resources:
            - image-builder-3
            artifacts:
            - external:
                id: qa-test-export
                store_id: qa-test-qa
                configuration:
                  options:
                    Destination: ${GO_PIPELINE_NAME}/${GO_PIPELINE_COUNTER}/${GO_STAGE_NAME}/${GO_STAGE_COUNTER}/${GO_JOB_NAME}
                    Source: cds-qa/Report*
            - test:
                source: cds-qa/Report*
                destination: testoutput
            tasks:
            - exec:
                arguments:
                - -c
                - eval $(aws ecr get-login --no-include-email --region ap-southeast-1
                  --registry-ids 841787149052)
                - ''
                command: bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - touch web_test.yaml
                command: sh
                working_directory: cds-qa
                run_if: passed
            - exec:
                arguments:
                - -c
                - cp -r etc/ cds-qa/
                command: sh
                run_if: passed
            - exec:
                arguments:
                - -c
                - /bin/python3 
                command: sh
                working_directory: cds-qa
                run_if: passed
            - exec:
                arguments:
                - -c
                - '/bin/execute-tops #{qa_config} #{test_plans}'
                command: sh
                working_directory: cds-qa
                run_if: passed
    parameters:
      test_plans: testcases/
      qa_config: ../qa-config/test-cds.txt
