format_version:9
pipelines:
  catalog-service-api-dev:
    group: catalog-service-api
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-config:
        git: git@bitbucket.org:suraz37/goci.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - deploy-run:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-unit-tests:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
            - exec:
                command: ./build
                run_if: passed
