format_version: 9
environments:
  maintainance:
    pipelines:
      - catalog-service-api
pipelines:
  qa-run-template:
    group: maintainance
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      qa-repository:
        git: '#{project_repo}'
        shallow_clone: false
        auto_update: false
        branch: '#{project_branch}'
        destination: '#{project}'
    stages:
    - qa-repository:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          qa-run:
            timeout: 0
            resources:
            - image-builder-3
            tasks:
            - exec:
                arguments:
                - -c
                - eval 
                command: bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - echo $PWD
                command: bash
                working_directory: '#{project}'
                run_if: passed
    parameters:
      project: catalog-service-api
      project_repo: git@github.com:centraldigital/catalog-service-api.git
      project_branch: main
      test_file: testcases/
      exclude_tag: incomplete
      plan_id: '22109'
      variable: '--variable ENV:staging'
