format_version: 9
environments:
  maintainance:
    pipelines:
      - catalog-service-api-gocd
pipelines:
  catalog-service-api-gocd:
    group: catalog-service-api
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      qa-run:
        git: git@bitbucket.org:centraltechnology/cds-core1.git
        shallow_clone: false
        auto_update: false
        branch: master
        destination: catalog-service-api
    stages:
    - deploy-run:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: true
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          deploy-run:
            timeout: 0
            resources:
            - image-builder-3
            tasks:
            - exec:
                arguments:
                - -c
                - eval $(aws ecr get-login --no-include-email --region ap-southeast-1
                  --registry-ids 841787149052)
                - ''
                command: bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - cp -r etc/ cds-qa/
                command: sh
                run_if: passed
            - exec:
                arguments:
                - -c
                - /bin/python3 
                command: sh
                working_directory: cds-qa
                run_if: passed
    parameters:
      test_plans: testcases/
