format_version: 9
environments:
  catalog-service-api:
    pipelines:
      - catalog-service-api-dev
pipelines:
  catalog-service-api-dev:
    group: catalog-service-api
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-config:
        git: git@github.com:suraz37/goci.git
        shallow_clone: false
        auto_update: false
        branch: main
        destination: catalog-service-api
        ignore_for_scheduling: true
    stages:
    - deploy-run:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          deploy-run:
            timeout: 0
            resources:
              - trivy
            tasks:
              - plugin:
                  configuration:
                    id: slack.task
                    version: "2.0"
                  options:
                    Message: "Deploying version "
                    IconOrEmoji: ""
                    Channel: catalog-service-api-deployer
                    Color: ""
                    DisplayName: GO-BOT
                    Title: 🚀 Starting OFM-FALCON Prod Deployment
                    ColorType: Warning
                    MarkdownInText: ""
                    FailOnError: ""
                    ChannelType: Channel
                  run_if: passed
              - exec:
                  arguments:
                    - -c
                    - ls
                  command: bash
                  working_directory: .
                  run_if: passed
